# permissions for end users to edit hypershiftdeployment.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hypershiftdeployment-editor-role
rules:
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - hypershiftdeployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - hypershiftdeployment/status
  verbs:
  - get
