---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hypershift-deployment-controller
  name: hypershift-deployment-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hypershift-deployment-controller
  template:
    metadata:
      labels:
        name: hypershift-deployment-controller
    spec:
      serviceAccountName: hyc
      containers:
      - image: quay.io/jpacker/hypershift-deployment-controller:latest
        name: hypershift-deployment-controller
        command: ["./manager", "--leader-elect"]
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: "20m"
            memory: "256Mi"
          requests:
            cpu: "0.1m"                     # Runs < 2m most of the time
            memory: "2Mi"                # Runs between 25-28Mi
